version: '3'
services:
  web:
    build: .
    deploy:
        mode: replicated
        replicas:3
  db:
    image: mariadb
    restart: always
    volumes:
      - "./data:/data"
    enviroment:
      MYSQL_ROOT_PASSWORD: lukaskas22
      MYSQL_DATABASE: data
      MYSQL_USER: lukas
      MYSQL_PASSWORD: lukaskas22
  adminer:
    image: adminer
    restart: always
    ports:
      -8080:8080
  nginx:
    image: nginx:latest
    volumes:
      - $PWD:/etc/nginx:ro
    depends_on:
      - web
    ports:
      - "80:80"
